/**
 * Aurora Bay — the board.
 *
 * An original 40-space circuit around a neon harbour city. Base values here are
 * the "100%" numbers; the engine applies the host's multipliers on top when a
 * game starts, and clients only ever see the multiplied result.
 */
import type { BoardSpace, PropertyGroup } from '../shared/types';

export const GROUPS: PropertyGroup[] = [
  { id: 'fringe', name: 'Harbour Fringe', color: '#9a6b4f' },
  { id: 'marina', name: 'The Marina', color: '#4fd3e8' },
  { id: 'oldtown', name: 'Old Town', color: '#e35fa8' },
  { id: 'arts', name: 'Arts Quarter', color: '#f08a34' },
  { id: 'heights', name: 'Sunset Heights', color: '#e5453f' },
  { id: 'neon', name: 'Neon District', color: '#f2d33c' },
  { id: 'ridge', name: 'Crystal Ridge', color: '#4ec96a' },
  { id: 'summit', name: 'The Summit', color: '#3a6ef0' },
  { id: 'transit', name: 'Transit Network', color: '#8f9bb3' },
  { id: 'works', name: 'City Works', color: '#b6a2ff' },
];

/** Rent ladders follow the classic power curve: base, then levels 1-5. */
export const BASE_BOARD: BoardSpace[] = [
  {
    id: 0,
    name: 'Launch Plaza',
    type: 'start',
    flavor: 'Where every circuit of the bay begins. Collect your stipend as you pass.',
  },
  {
    id: 1,
    name: 'Sunset Row',
    type: 'property',
    group: 'fringe',
    price: 60,
    rent: [2, 10, 30, 90, 160, 250],
    buildCost: 50,
    flavor: 'Faded awnings and the best noodle cart in the city.',
  },
  { id: 2, name: 'City Pulse', type: 'event', flavor: 'The city feed never sleeps.' },
  {
    id: 3,
    name: 'Tidewalk Lane',
    type: 'property',
    group: 'fringe',
    price: 60,
    rent: [4, 20, 60, 180, 320, 450],
    buildCost: 50,
    flavor: 'Boardwalk planks worn smooth by a century of boots.',
  },
  { id: 4, name: 'Civic Levy', type: 'tax', amount: 200, flavor: 'The harbour authority always gets paid.' },
  {
    id: 5,
    name: 'Harbour Rail',
    type: 'transport',
    group: 'transit',
    price: 200,
    rent: [25, 50, 100, 200],
    flavor: 'Salt-crusted platforms and a very punctual tram.',
  },
  {
    id: 6,
    name: 'Beacon Street',
    type: 'property',
    group: 'marina',
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    buildCost: 50,
    flavor: 'The lighthouse sweep lands here every eleven seconds.',
  },
  { id: 7, name: 'City Pulse', type: 'event', flavor: 'The city feed never sleeps.' },
  {
    id: 8,
    name: 'Coral Way',
    type: 'property',
    group: 'marina',
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    buildCost: 50,
    flavor: 'Reef-glass mosaics run the length of the pavement.',
  },
  {
    id: 9,
    name: 'Lantern Quay',
    type: 'property',
    group: 'marina',
    price: 120,
    rent: [8, 40, 100, 300, 450, 600],
    buildCost: 50,
    flavor: 'Ten thousand paper lanterns, replaced every spring.',
  },
  {
    id: 10,
    name: 'Holding Yard',
    type: 'detention',
    flavor: 'A container yard with a very slow gate. Just visiting?',
  },
  {
    id: 11,
    name: 'Amber Court',
    type: 'property',
    group: 'oldtown',
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    buildCost: 100,
    flavor: 'Sandstone arches lit gold at dusk.',
  },
  {
    id: 12,
    name: 'Fusion Works',
    type: 'utility',
    group: 'works',
    price: 150,
    utilityMultipliers: [4, 10],
    flavor: 'Hums at a frequency that makes your teeth itch.',
  },
  {
    id: 13,
    name: 'Copper Lane',
    type: 'property',
    group: 'oldtown',
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    buildCost: 100,
    flavor: 'Every roof here has gone green with age.',
  },
  {
    id: 14,
    name: 'Vermilion Walk',
    type: 'property',
    group: 'oldtown',
    price: 160,
    rent: [12, 60, 180, 500, 700, 900],
    buildCost: 100,
    flavor: 'Red banners strung between balconies, year round.',
  },
  {
    id: 15,
    name: 'Skyline Rail',
    type: 'transport',
    group: 'transit',
    price: 200,
    rent: [25, 50, 100, 200],
    flavor: 'Runs the ridge line, four hundred metres up.',
  },
  {
    id: 16,
    name: 'Mosaic Avenue',
    type: 'property',
    group: 'arts',
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    buildCost: 100,
    flavor: 'The pavement itself is a listed artwork.',
  },
  { id: 17, name: 'City Pulse', type: 'event', flavor: 'The city feed never sleeps.' },
  {
    id: 18,
    name: 'Kiln Street',
    type: 'property',
    group: 'arts',
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    buildCost: 100,
    flavor: 'Glassblowers work through the night here.',
  },
  {
    id: 19,
    name: 'Gallery Row',
    type: 'property',
    group: 'arts',
    price: 200,
    rent: [16, 80, 220, 600, 800, 1000],
    buildCost: 100,
    flavor: 'Nineteen galleries. Eighteen of them serve coffee.',
  },
  {
    id: 20,
    name: 'Aurora Gardens',
    type: 'rest',
    flavor: 'Terraced glass-houses above the bay. Nothing to pay, nothing to do.',
  },
  {
    id: 21,
    name: 'Solstice Drive',
    type: 'property',
    group: 'heights',
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    buildCost: 150,
    flavor: 'Aligned so the midsummer sun runs straight down the road.',
  },
  { id: 22, name: 'City Pulse', type: 'event', flavor: 'The city feed never sleeps.' },
  {
    id: 23,
    name: 'Ember Heights',
    type: 'property',
    group: 'heights',
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    buildCost: 150,
    flavor: 'Terracotta terraces stacked up the hillside.',
  },
  {
    id: 24,
    name: 'Crimson Terrace',
    type: 'property',
    group: 'heights',
    price: 240,
    rent: [20, 100, 300, 750, 925, 1100],
    buildCost: 150,
    flavor: 'The most photographed balcony in Aurora Bay.',
  },
  {
    id: 25,
    name: 'Vector Rail',
    type: 'transport',
    group: 'transit',
    price: 200,
    rent: [25, 50, 100, 200],
    flavor: 'Maglev. Doors close whether or not you are through them.',
  },
  {
    id: 26,
    name: 'Neon Harbour',
    type: 'property',
    group: 'neon',
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    buildCost: 150,
    flavor: 'Signage reflected in black water. The postcard shot.',
  },
  {
    id: 27,
    name: 'Voltage Street',
    type: 'property',
    group: 'neon',
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    buildCost: 150,
    flavor: 'Arcades, all night, all noise.',
  },
  {
    id: 28,
    name: 'Aqua Reservoir',
    type: 'utility',
    group: 'works',
    price: 150,
    utilityMultipliers: [4, 10],
    flavor: 'Holds the whole ridge worth of meltwater.',
  },
  {
    id: 29,
    name: 'Lumen Boulevard',
    type: 'property',
    group: 'neon',
    price: 280,
    rent: [24, 120, 360, 850, 1025, 1200],
    buildCost: 150,
    flavor: 'Six lanes of light, no cars allowed.',
  },
  {
    id: 30,
    name: 'Detained',
    type: 'goto_detention',
    flavor: 'Harbour patrol has some questions about your paperwork.',
  },
  {
    id: 31,
    name: 'Crystal Heights',
    type: 'property',
    group: 'ridge',
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    buildCost: 200,
    flavor: 'Built into the seam itself. The walls glow faintly.',
  },
  {
    id: 32,
    name: 'Prism Park',
    type: 'property',
    group: 'ridge',
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    buildCost: 200,
    flavor: 'Every fountain throws a rainbow at noon.',
  },
  { id: 33, name: 'City Pulse', type: 'event', flavor: 'The city feed never sleeps.' },
  {
    id: 34,
    name: 'Quartz Avenue',
    type: 'property',
    group: 'ridge',
    price: 320,
    rent: [28, 150, 450, 1000, 1200, 1400],
    buildCost: 200,
    flavor: 'White stone, white light, eye-watering rents.',
  },
  {
    id: 35,
    name: 'Orbital Rail',
    type: 'transport',
    group: 'transit',
    price: 200,
    rent: [25, 50, 100, 200],
    flavor: 'The line that leaves the ground and does not come back.',
  },
  { id: 36, name: 'City Pulse', type: 'event', flavor: 'The city feed never sleeps.' },
  {
    id: 37,
    name: 'Grand Plaza',
    type: 'property',
    group: 'summit',
    price: 350,
    rent: [35, 175, 500, 1100, 1300, 1500],
    buildCost: 200,
    flavor: 'Where the city signs its treaties and its evictions.',
  },
  {
    id: 38,
    name: 'Luxury Surcharge',
    type: 'tax',
    amount: 100,
    flavor: 'Assessed on anyone who looks like they can afford it.',
  },
  {
    id: 39,
    name: 'Aurora Spire',
    type: 'property',
    group: 'summit',
    price: 400,
    rent: [50, 200, 600, 1400, 1700, 2000],
    buildCost: 200,
    flavor: 'The tallest address in the bay. The view costs extra.',
  },
];

export const BOARD_SIZE = BASE_BOARD.length;

/** Spaces that can be owned. */
export function isOwnable(space: { type: string }): boolean {
  return space.type === 'property' || space.type === 'transport' || space.type === 'utility';
}

export function groupById(id: string | undefined): PropertyGroup | undefined {
  return GROUPS.find((g) => g.id === id);
}
